# this configuration will be used to validate examples provided in this repo,
# against the official schemas
- name: application-description
  description: Validate ApplicationDescription examples
  schema: spec/data-models/application-description.linkml.yaml
  target_class: ApplicationDescription
  examples:
    valid: spec/examples/valid
    invalid: spec/examples/invalid

- name: application-deployment
  description: Validate ApplicationDeployment examples
  schema: spec/data-models/application-deployment.linkml.yaml
  target_class: ApplicationDeployment
  examples:
    valid: spec/examples/valid
    invalid: spec/examples/invalid
