- name: application-deployment
  description: Generates markdown for ApplicationDeployment
  doc_template_dir: spec/templates/class-pages/main-classes
  input:
    schema: spec/data-models/application-deployment.linkml.yaml
  output:
    md: spec/generated/class-pages/application-deployment.md

- name: application-description
  description: Generates markdown for ApplicationDescription
  doc_template_dir: spec/templates/class-pages/main-classes
  input:
    schema: spec/data-models/application-description.linkml.yaml
  output:
    md: spec/generated/class-pages/application-description.md

- name: deployment-status
  description: Generates markdown for DeploymentStatus
  doc_template_dir: spec/templates/class-pages/main-classes
  input:
    schema: spec/data-models/deployment-status.linkml.yaml
  output:
    md: spec/generated/class-pages/deployment-status.md

- name: desired-state-manifest
  description: Generates markdown for DesiredStateManifest
  doc_template_dir: spec/templates/class-pages/main-classes
  input:
    schema: spec/data-models/desired-state-manifest.linkml.yaml
  output:
    md: spec/generated/class-pages/desired-state-manifest.md

- name: device-capabilities
  description: Generates markdown for DeviceCapabilities
  doc_template_dir: spec/templates/class-pages/main-classes
  input:
    schema: spec/data-models/device-capabilities.linkml.yaml
  output:
    md: spec/generated/class-pages/device-capabilities.md

- name: device-onboarding
  description: Generates markdown for DeviceOnboarding
  doc_template_dir: spec/templates/class-pages/main-classes
  input:
    schema: spec/data-models/device-onboarding.linkml.yaml
  output:
    md: spec/generated/class-pages/device-onboarding.md

- name: data-models
  description: Generates markdown for entire Margo data model
  doc_template_dir: spec/templates/class-pages/main-classes
  input:
    schema: spec/data-models/margo.linkml.yaml
  output:
    directory: spec/generated/class-pages/all-data-models
