- name: DataModel-ClassDiagram
  schema: spec/data-models/margo.linkml.yaml
  classes_to_render: [] # will render all the classes
  pipeline:
    - explicitly_add_uml_relationship: "DeploymentAnnotations ..> ApplicationDescription"
    - explicitly_add_uml_relationship: "DeploymentStatusManifest ..> ApplicationDeployment"
    - explicitly_add_uml_relationship: "DesiredStateManifest ..> ApplicationDeployment"
  output:
    svg: spec/generated/class-diagrams/AllClasses.svg

- name: ApplicationDescription-ClassDiagram
  schema: spec/data-models/application-description.linkml.yaml
  classes_to_render:
    - ApplicationDescription
    - ApplicationMetadata
    - Parameter
    - Configuration
    - DeploymentProfileDescription
    - TextValidationSchema
    - BooleanValidationSchema
    - NumericIntegerValidationSchema
    - NumericDoubleValidationSchema
    - SelectValidationSchema
  pipeline:
    - delete_uml_block: "Component.*{$"
  output:
    svg: spec/generated/class-diagrams/ApplicationDescription.svg

- name: DeploymentStatusManifest-ClassDiagram
  schema: spec/data-models/margo.linkml.yaml
  classes_to_render:
    - DeploymentStatusManifest
    - ApplicationDeployment
    - DeploymentProfile
  pipeline:
    - explicitly_add_uml_relationship: "DeploymentStatusManifest ..> ApplicationDeployment"
    - explicitly_add_uml_relationship: "ComponentStatus ..> Component"
  output:
    svg: spec/generated/class-diagrams/DeploymentStatusManifest.svg

- name: DesiredStateManifest-ClassDiagram
  schema: spec/data-models/margo.linkml.yaml
  classes_to_render:
    - DesiredStateManifest
  pipeline:
    - explicitly_add_uml_relationship: "DesiredStateManifest ..> ApplicationDeployment"
  output:
    svg: spec/generated/class-diagrams/DesiredStateManifest.svg

- name: DeviceCapabilities-ClassDiagram
  schema: spec/data-models/margo.linkml.yaml
  classes_to_render:
    - DeviceCapabilitiesManifest
    - Properties
    - Resources
  pipeline: []
  output:
    svg: spec/generated/class-diagrams/DeviceCapabilities.svg

- name: ApplicationDeployment-ClassDiagram
  schema: spec/data-models/application-deployment.linkml.yaml
  classes_to_render:
    - ApplicationDeployment
    - DeploymentMetadata
    - DeploymentAnnotations
    - Spec
    - Parameter
    - DeploymentProfile
    - ComposeDeploymentProfile
    - HelmDeploymentProfile
    - Component
  pipeline:
    - explicitly_add_uml_relationship: "DeploymentAnnotations ..> ApplicationDescription"
  output:
    svg: spec/generated/class-diagrams/ApplicationDeployment.svg

- name: DeviceOnboarding-ClassDiagram
  schema: spec/data-models/device-onboarding.linkml.yaml
  classes_to_render: []
  pipeline: []
  output:
    svg: spec/generated/class-diagrams/DeviceOnboarding.svg
