site_name: System Design
docs_dir: system-design

nav:
  - Introduction: index.md
  - Example System Design: margo-overview/introduction-system-design.md
  - Personas: margo-overview/personas.md
  - Technical Lexicon: margo-overview/technical-lexicon.md
  - Application Distribution:
      - Application Package Definition: app-interoperability/application-package-definition.md
      - Workload Orchestration to App Registry Interactions: app-interoperability/workload-orch-to-app-reg-interaction.md
  - Device Interoperability:
      - Device Requirements: device-interoperability/device-requirements.md
      - Observability: app-interoperability/observability.md
  - Orchestration:
      - Workload:
          - Management API: orchestration/workload/workload-management-interface-breakdown.md
          - Onboarding: orchestration/workload/workload-orchestration-edge-onboarding.md
          - Device Capabilities: orchestration/workload/device-capability-reporting.md
          - Workload Deployment: orchestration/workload/workload-deployment.md
  ##    - Device:
  ##  - Appendix:
  ##    - Management API Definition: margo-overview/personas.md
  - Management API Reference:
      - Overview: margo-api-reference/margo-api-specification.md
      - Workload API:
          - Desired State API:
              - Desired State: margo-api-reference/workload-api/desired-state-api/desired-state.md
          - Device API:
              - Device Capabilities: margo-api-reference/workload-api/device-api/device-capabilities.md
              - Deployment Status: margo-api-reference/workload-api/device-api/deployment-status.md
          - Onboarding API:
              - Device Onboarding: margo-api-reference/workload-api/onboarding-api/device-onboarding.md
              - Certificate Download: margo-api-reference/workload-api/onboarding-api/rootca-download.md

theme:
  name: material
  features:
    #- navigation.tabs
    #- navigation.settings
    #- navigation.top
    - navigation.tracking
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotations
    - content.code.copy
  language: en
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  logo: assets/margo_white.svg
  favicon: assets/favicon.ico
  palette:
    scheme: margo

markdown_extensions:
  - toc:
      toc_depth: 2

extra_css:
  - css/margo.css

extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#generator-notice
  generator: true
  homepage: https://margo.org
  copyright: Copyright &copy; 2024 Margo
  reponame: !ENV [GITHUB_REPOSITORY, "margo/specification"]
  commit: !ENV [GITHUB_SHA, "<unknown>"]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/margo
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/margo_project
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/margoproject/about/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Margoinitiative
    - icon: fontawesome/brands/discord
      link: http://chat.margo.org/

plugins:
  - search
  - markdownextradata:
      jinja_options:
        variable_start_string: =@=
        variable_end_string: =@=
  - privacy
