site_name: System Design
docs_dir: system-design

nav:
  - Introduction: index.md
  - Envisioned System Design: margo-overview/introduction-system-design.md
  - Personas: margo-overview/personas.md
  - Technical Lexicon: margo-overview/technical-lexicon.md
  - App Interoperability:
    - Application Package Definition: app-interoperability/application-package-definition.md
    - Device Capability Discovery: app-interoperability/device-capability-discovery.md
    - Workload Orchestration Software: app-interoperability/workload-orchestration-software.md
    - Workload Orchestration to App Registry Interactions: app-interoperability/workload-orch-to-app-reg-interaction.md
    - Workload Orchestrator App Configuration and Deployment: app-interoperability/orchestator-app-config-deploy.md
    - Workload Orchestration Agent: app-interoperability/workload-orchestration-agent.md
    - Observability: app-interoperability/observability.md
  - Device Interoperability:
    - Device Requirements: device-interoperability/device-requirements.md

theme:
  name: material
  features:
    #- navigation.tabs
    #- navigation.settings
    #- navigation.top
    - navigation.tracking
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotations
    - content.code.copy
  language: en
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  logo: assets/margo_white.svg
  favicon: assets/favicon.ico
  palette:
    scheme: margo

extra_css:
  - css/margo.css

extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#generator-notice
  generator: true
  homepage: https://margo.org
  copyright: Copyright &copy; 2024 Margo
  reponame: !ENV [GITHUB_REPOSITORY, 'margo/specification']
  commit: !ENV [GITHUB_SHA, '<unknown>']
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/margo
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/margo_project
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/margoproject/about/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Margoinitiative
    - icon: fontawesome/brands/discord
      link: http://chat.margo.org/

plugins:
  - search
  - markdownextradata:
      jinja_options:
        variable_start_string: =@=
        variable_end_string: =@=
  - privacy
