- name: workload-management-api
  description: Generates aggregated OpenAPI specification for Margo models
  input:
    schema: spec/data-model/margo.linkml.yaml
    template: spec/tools/workload-management-api.openapi.template.yaml
  output:
    yaml: spec/generated/openapi/workload-management-api.openapi.yaml
